/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buoi7;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Huyen
 */
public class PickleballView extends javax.swing.JFrame {

    /**
     * Creates new form PickleballView
     */
    ArrayList<Pickleball> list = new ArrayList<>();
    PickleballService service = new PickleballService();
    DefaultTableModel defaultTableModel = new DefaultTableModel();
    DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel();

    public PickleballView() {
        initComponents();
        list = service.getAll();
        loadComboboxModel();
        loadDataTable();
        fillData(0);
    }

    private void loadDataTable() {
        defaultTableModel
                = (DefaultTableModel) tblPickleball.getModel();
        defaultTableModel.setRowCount(0);
        for (Pickleball pickleball : list) {
            defaultTableModel.addRow(new Object[]{
                pickleball.getMa(),
                pickleball.getTen(),
                pickleball.getThuongHieu(),
                pickleball.getGia(),
                pickleball.getSoLuong(),
                pickleball.getTrangThai() == 1 ? "Mở bán" : "Ngừng bán"
            });
        }
    }

    private void loadComboboxModel() {
        defaultComboBoxModel.addElement("Wilson");
        defaultComboBoxModel.addElement("Joola");
        cboThuongHieu.setModel(defaultComboBoxModel);
    }

    private void fillData(int index) {
        Pickleball pick = list.get(index);//lấy đối tượng tại vị trí index trong list
        txtMa.setText(pick.getMa());
        txtTen.setText(pick.getTen());
        cboThuongHieu.setSelectedItem(pick.getThuongHieu());
        txtGia.setText(String.valueOf(pick.getGia()));
        txtSoLuong.setText(String.valueOf(pick.getSoLuong()));
        if (pick.getTrangThai() == 1) {
            rdoMoBan.setSelected(true);
        } else {
            rdoNgungBan.setSelected(true);
        }
    }

    private Pickleball getValueForm() {
        return new Pickleball(
                txtMa.getText(),
                txtTen.getText(),
                String.valueOf(cboThuongHieu.getSelectedItem()),
                Double.parseDouble(txtGia.getText()),
                Integer.parseInt(txtSoLuong.getText()),
                rdoMoBan.isSelected() ? 1 : 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        cboThuongHieu = new javax.swing.JComboBox<>();
        txtGia = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        rdoMoBan = new javax.swing.JRadioButton();
        rdoNgungBan = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPickleball = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mã:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 55, 37, -1));

        jLabel2.setText("Tên:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 105, 37, -1));

        jLabel3.setText("Thương hiệu:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 156, 88, -1));

        jLabel4.setText("Giá:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 55, 37, -1));

        jLabel5.setText("Số lượng:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 105, 83, -1));

        jLabel6.setText("Tình trạng:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 156, 72, -1));
        getContentPane().add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 52, 147, -1));
        getContentPane().add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 102, 147, -1));

        cboThuongHieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cboThuongHieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 153, 148, -1));
        getContentPane().add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 52, 100, -1));
        getContentPane().add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 102, 90, -1));

        buttonGroup1.add(rdoMoBan);
        rdoMoBan.setText("Mở bán");
        getContentPane().add(rdoMoBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 154, 98, -1));

        buttonGroup1.add(rdoNgungBan);
        rdoNgungBan.setText("Ngừng bán");
        getContentPane().add(rdoNgungBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 193, 98, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("QUẢN LÝ VỢT PICKLEBALL");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 6, 271, -1));

        tblPickleball.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Thương hiệu", "Giá", "Số lượng", "Tình trạng"
            }
        ));
        tblPickleball.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPickleballMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPickleball);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 684, 298));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPickleballMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPickleballMouseClicked
        int index = tblPickleball.getSelectedRow();
        fillData(index);
    }//GEN-LAST:event_tblPickleballMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        //confirm tự làm
        Pickleball pick = getValueForm();
        service.addPick(pick);
        loadDataTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int rowIndex = tblPickleball.getSelectedRow();
        if (rowIndex != -1) {
            service.deletePick(rowIndex);
            loadDataTable();
            //thông báo thành công tự làm
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng muốn xóa!");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int rowIndex = tblPickleball.getSelectedRow();
        if (rowIndex != -1) {
            Pickleball pickNew = getValueForm();//tạo đối tượng mới với thông tin từ form
            service.updatePick(rowIndex, pickNew);//gọi update bên service
            loadDataTable();
            //thông báo thành công tự làm
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng muốn sửa!");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickleballView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickleballView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickleballView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickleballView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PickleballView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboThuongHieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoMoBan;
    private javax.swing.JRadioButton rdoNgungBan;
    private javax.swing.JTable tblPickleball;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
